[bot]
token = "BOT_TOKEN_HERE"
key = "e!"

[settings]
	server_id = 123123123123
	default_image_name = "default.png"

[events]

	[events.fourth]
		image_name = "fourth.png"
		date_start = "7-3"
		date_end = "7-5"

	[events.halloween]
		image_name = "halloween.png"
		date_start = "10-20"
		date_end = "11-1"

	[events.christmas]
		image_name = "christmas.png"
		date_start = "12-10"
		date_end = "1-1"